spring:
  application:
    name: eureka-user
  jpa:
    show-sql: true
server:
  port: 8005
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    hostname: localhost