spring:
                application:
                  name: eureka-customer
                jpa:
                  show-sql: true
                server:
                  port: 8002
                eureka:
                  client:
                    register-with-eureka: true
                    fetch-registry: true
                    service-url:
                      defaultZone: http://localhost:8003/eureka
                  instance:
                    hostname: localhost